DEBUG=1

STATE_LOGIN = 1
STATE_SHOW_OPTIONS = 2
STATE_CREATE = 3
STATE_JOIN = 4
STATE_IN_ROOM = 5

TYPE_MESSAGE_CONTENT=11
TYPE_MESSAGE_ROOM=12
TYPE_MESSAGE_ROOMS=16
TYPE_MESSAGE_LOGIN=13
TYPE_MESSAGE_BOOLEAN=14
TYPE_MESSAGE_IMAGE_FRAME=15
TYPE_MESSAGE_AUDIO_FRAME=15

ACTION_CHECK_LOGIN=21
ACTION_CREATE_ROOM=22
ACTION_JOIN_ROOM=23
ACTION_CONTENT=24
ACTION_IMAGE_FRAME=25
ACTION_AUDIO_FRAME=26
ACTION_SHOW_ROOM=27
